name = "image-background-remover"
main = "functions/_worker.js"
compatibility_date = "2024-03-18"

[build]
command = ""
publish = "."

[vars]
REMOVE_BG_API_KEY = "mUHDVBxMYtsp3Da9qR1izXmA"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200